/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projeto03.poo1;

import javafx.scene.paint.Color;

/**
 *
 * @author adeli
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        tfCampo1 = new javax.swing.JTextField();
        tfCampo2 = new javax.swing.JTextField();
        tfCampo3 = new javax.swing.JTextField();
        btnAcao1 = new javax.swing.JButton();
        btnAcao2 = new javax.swing.JButton();
        btnAcao3 = new javax.swing.JButton();
        bntAcao5 = new javax.swing.JButton();
        bntAcao4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTexto1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(0, 153, 153));
        lblTexto1.setText("1° label");

        lblTexto2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(204, 0, 0));
        lblTexto2.setText("segundo label");

        lblTexto3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(51, 153, 0));
        lblTexto3.setText("terceirona");

        tfCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCampo1ActionPerformed(evt);
            }
        });

        btnAcao1.setText("Ação 01");
        btnAcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao1ActionPerformed(evt);
            }
        });

        btnAcao2.setText("Ação 02");
        btnAcao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao2ActionPerformed(evt);
            }
        });

        btnAcao3.setText("Ação 03");
        btnAcao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcao3ActionPerformed(evt);
            }
        });

        bntAcao5.setText("Ação 05");
        bntAcao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAcao5ActionPerformed(evt);
            }
        });

        bntAcao4.setText("Ação 04");
        bntAcao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAcao4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAcao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTexto1)
                    .addComponent(tfCampo1))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfCampo2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAcao2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTexto3)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCampo3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAcao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(bntAcao4)
                .addGap(76, 76, 76)
                .addComponent(bntAcao5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTexto1)
                    .addComponent(lblTexto2)
                    .addComponent(lblTexto3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao1)
                    .addComponent(btnAcao2)
                    .addComponent(btnAcao3))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAcao4)
                    .addComponent(bntAcao5))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCampo1ActionPerformed

    private void btnAcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao1ActionPerformed
        
        // Existe um padrão utilizado no meio da programação chamado. 
        // GET e SET
        // Get serve para recuperar algo ou algum valor.
        // Set serve para alterar alguma característica.
        
        lblTexto1.setText("Alguem clicou!");
        
    }//GEN-LAST:event_btnAcao1ActionPerformed

    private void btnAcao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao2ActionPerformed
        
        // Criando variavel que armazena conteudo do input
        
        // String texto = tfCampo2.getText();
        // lblTexto2.setText(texto);
        
        lblTexto2.setText(tfCampo2.getText());
        
    }//GEN-LAST:event_btnAcao2ActionPerformed

    private void btnAcao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcao3ActionPerformed
        
        // Exemplo de troca de cores dos objetos
        
        // Cores pré definidas
        lblTexto3.setForeground(java.awt.Color.darkGray);
        
        // Valores hexa
        lblTexto3.setForeground(java.awt.Color.decode("#e67e22"));
        
    }//GEN-LAST:event_btnAcao3ActionPerformed

    private void bntAcao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAcao4ActionPerformed
        
        String texto = tfCampo1.getText();
        lblTexto1.setText(texto);        
        lblTexto2.setText(texto);
        lblTexto3.setText(texto);

        
    }//GEN-LAST:event_bntAcao4ActionPerformed

    private void bntAcao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAcao5ActionPerformed
        
        
         lblTexto2.setForeground(lblTexto1.getForeground());         
         lblTexto3.setForeground(lblTexto1.getForeground());

        
    }//GEN-LAST:event_bntAcao5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAcao4;
    private javax.swing.JButton bntAcao5;
    private javax.swing.JButton btnAcao1;
    private javax.swing.JButton btnAcao2;
    private javax.swing.JButton btnAcao3;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JTextField tfCampo1;
    private javax.swing.JTextField tfCampo2;
    private javax.swing.JTextField tfCampo3;
    // End of variables declaration//GEN-END:variables
}
